### ISSUE TITLE
BUG: Failing to apply GH Standards

### ISSUE THREAD

**Issue by madpah** [sonatype-nexus-community/github-management#5]
See https://github.com/sonatype-nexus-community/github-management/actions/runs/11433723947/job/31806150629

Failing to run post #3 ? with error:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/github-management/github-management/github_standards/__main__.py", line 80, in <module>
    main()
  File "/home/runner/work/github-management/github-management/github_standards/__main__.py", line 74, in main
    apply_standards_to_repo(repo=repo, do_actual_work=True)
  File "/home/runner/work/github-management/github-management/github_standards/__main__.py", line 46, in apply_standards_to_repo
    check_and_apply_standard_properties_to_branch(repo, main_b, do_actual_work)
  File "/home/runner/work/github-management/github-management/github_standards/standards.py", line 62, in check_and_apply_standard_properties_to_branch
    if getattr(branch.get_protection(), prop) != val:
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/github-management-e651j1wj-py3.12/lib/python3.12/site-packages/github/Branch.py", line 129, in get_protection
    headers, data = self._requester.requestJsonAndCheck(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/github-management-e651j1wj-py3.12/lib/python3.12/site-packages/github/Requester.py", line 550, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/github-management-e651j1wj-py3.12/lib/python3.12/site-packages/github/Requester.py", line 611, in __check
    raise self.createException(status, responseHeaders, data)
github.GithubException.GithubException: 404 {"message": "Branch not protected", "documentation_url": "https://docs.github.com/rest/branches/branch-protection#get-branch-protection", "status": "404"}
```

FYI @bhamail

**Comment by madpah** [comment]
Fixed via https://github.com/sonatype-nexus-community/github-management/commit/0ef4782663084c143cd52186ad246e437b8e1ac3

Working now ;-) 

https://github.com/sonatype-nexus-community/github-management/actions/runs/11435109874/job/31809877500
