### ISSUE TITLE
BUG: Failing to apply standards 04-Dec-2024

### ISSUE THREAD

**Issue by madpah** [sonatype-nexus-community/github-management#7]
See https://github.com/sonatype-nexus-community/github-management/actions/runs/12153552323/job/33891842934

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/github-management/github-management/github_standards/__main__.py", line 80, in <module>
    main()
  File "/home/runner/work/github-management/github-management/github_standards/__main__.py", line 74, in main
    apply_standards_to_repo(repo=repo, do_actual_work=True)
  File "/home/runner/work/github-management/github-management/github_standards/__main__.py", line 46, in apply_standards_to_repo
    check_and_apply_standard_properties_to_branch(repo, main_b, do_actual_work)
  File "/home/runner/work/github-management/github-management/github_standards/standards.py", line 82, in check_and_apply_standard_properties_to_branch
    branch.edit_protection(**standard_branch_protection)
  File "/home/runner/.cache/pypoetry/virtualenvs/github-management-e651j1wj-py3.12/lib/python3.12/site-packages/github/Branch.py", line 307, in edit_protection
    headers, data = self._requester.requestJsonAndCheck(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/github-management-e651j1wj-py3.12/lib/python3.12/site-packages/github/Requester.py", line 550, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/github-management-e651j1wj-py3.12/lib/python3.12/site-packages/github/Requester.py", line 611, in __check
    raise self.createException(status, responseHeaders, data)
github.GithubException.GithubException: 404 {"message": "Branch protection has been disabled on this repository.", "documentation_url": "https://docs.github.com/rest/branches/branch-protection#update-branch-protection", "status": "404"}
```

Caused by:
```
Reviewing Repo: cargo-pants...
    Assessing Standards for cargo-pants
    Branch Branch(name="main") is not protected in cargo-pants
    Setting Standards for cargo-pants - missing 
FAIL:   Failed to apply branch standards for cargo-pants
```

**Comment by madpah** [comment]
ROOT CAUSE:
![Screenshot 2024-12-04 at 08 24 08](https://github.com/user-attachments/assets/11465e84-39f9-4440-9e41-78c7ba3d8521)

@bhamail any thoughts / ideas?

**Comment by bhamail** [comment]
"resolved" by putting back the protections. Not sure we need to actually "fix" the automated restoration of branch protections, so long as the automated detection of deviation from standard still works.
